### ISSUE TITLE
US01 - Eu, como administrador, quero obter dados de visualizações de vídeos, para analisar o engajamento dos usuários.

### ISSUE THREAD

**Issue by victorleaoo** [fga-eps-mds/2024.1-UnB-TV-DOC#29]
# Tarefas

## Gerais

- [x] Protótipo
- [x] Testes
- [x] Deploy

### 1. Implementar Coleta de Dados de Visualizações
- [ ] Extrair dados de visualização da api do eduplay para capturar dados de visualizações por vídeo, sem necessidade de armazenamento no banco de dados.
- [ ] Obter metadados do vídeo: id, título, descrição, categoria e número de visualizações.

### 2. Desenvolver Página com os Dados
- [ ] Criar filtros de busca para os vídeos: id, título, descrição e categoria.
- [ ] Listar cada vídeo com suas informações e quantidade de visualizações.
- [ ] Possibilitar a ordenação crescente ou decrescente por quantidade de visualização, ao clicar na coluna.

# Critérios de Aceitação

### 1. Coleta de Dados de Visualizações
- [ ] O sistema deve coletar dados de visualizações em tempo real (de acordo com a api do eduplay).
- [ ] O sistema deve coletar dados dos metadados dos vídeos em tempo real (de acordo com a api do eduplay).

### 2. Página com Dados
- [ ] Ao clicar no direcionar da página no menu lateral, o usuário é direcionado para a página de dados de visualizações.
- [ ] O sistema deve fornecer uma tabela com os principais metadados dos vídeos e suas visualizações, com opção de ordenar por quantidade de visualização, de forma crescente ou decrescente, ao clicar no nome da coluna.
- [ ] Os filtros de busca devem funcionar de forma conjunta, por exemplo, caso uma categoria seja filtrada e, em seguida, o título, devem aparecer apenas títulos da categoria filtrada.

# Protótipo
![image](https://github.com/user-attachments/assets/a7c7b82d-17f3-4838-bf04-c125a4e1bfd4)

**Comment by caioleboutte** [comment]
HOMOLOGADO. Layout passível de melhorias mas o presente já está bom.

**Comment by victorleaoo** [comment]
@caioleboutte após estudar a API do eduplay, vemos que não há a informação de data de publicação... 
o que temos:

- id;
- titulo;
- descrição;
- palavras-chave;
- visibilidade (publico, privado...);
- duração;
- quantidade de visualizações / acessos;
- o "dono" do vídeo.

gostaria de adicionar algum outro no lugar da data de publicação?
