### ISSUE TITLE
US02 - Eu, como administrador, quero obter dados de visualizações por categorias, para entender quais tópicos são mais populares.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#30]
# Tarefas

## Gerais

- [x] Protótipo
- [x] Testes
- [x] Deploy

### 1. Implementar Coleta de Dados de Visualizações
- [ ] Extrair dados de visualização da api do eduplay para capturar dados de visualizações por categoria (agrupando), sem necessidade de armazenamento no banco de dados.
- [ ] Obter as métricas de número de vídeos por categoria e calcular visualizações por vídeo em cada categoria.

### 2. Desenvolver Página com os Dados
- [ ] Criar filtro de busca por categoria, permitindo a seleção de mais de uma categoria (check box)
- [ ] Listar cada categoria com: nome da categoria, número de vídeos, quantidade de visualizações e quantidade de visualizações por vídeo em categoria.
- [ ] Possibilitar a ordenação crescente ou decrescente por número de vídeos, quantidade de visualizações e visualização por vídeo, ao clicar na coluna.

# Critérios de Aceitação

### 1. Coleta de Dados de Visualizações
- [ ] O sistema deve coletar dados de visualizações em tempo real (de acordo com api do eduplay).
- [ ] O sistema deve coletar dados de quantidade de vídeos em uma categoria em tempo real (de acordo com api do eduplay).

### 2. Página com Dados
- [ ] Ao clicar no direcionar da página no menu lateral, o usuário é direcionado para a página de dados de visualizações por categoria.
- [ ] O sistema deve fornecer uma tabela com os dados de visualização de categoria, com a possibilidade de ordenar por número de vídeos, quantidade de visualizações e visualização por vídeo, de forma crescente ou decrescente, ao clicar no nome da coluna (se torna azul).
- [ ]  Um filtro com os tipos de categoria, mas podendo escolher mais que uma, deve ser disponível.

# Protótipo
![image](https://github.com/user-attachments/assets/8c674b9c-8a3b-45fe-8019-36de639d05fb)

**Comment by caioleboutte** [comment]
HOMOLOGADO. Idem do anterior. passível de melhorias de layout mas está bom!
