### ISSUE TITLE
US06 - Eu, como administrador, quero ver as estatísticas de visualizações por categoria, para monitorar o desempenho por tópico.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#32]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Exportação dos dados

- [ ] Implementar botão na tela de dados de vídeos para exportar todos os dados de visualização dos vídeos para arquivo .xlsx.
- [ ] Implementar botão na tela de dados de categorias para exportar todos os dados de visualização das categorias para arquivo .xlsx.

## Criação da Página de Estatísticas por Categoria

- [ ] Implementar a criação da página de estatísticas de visualizações por categoria.

## Criação dos Gráficos

- [ ] Implementar um gráfico de barras para mostrar a quantidade de visualizações por categoria.
- [ ] Implementar um gráfico de pizza para mostrar a proporção de visualizações por categoria.
- [ ] Implementar um gráfico de barras para mostrar a quantidade de vídeos por categoria.
- [ ] Implementar um gráfico de pizza para mostrar a proporção de vídeos por categoria.
- [ ] Implementar um gráfico de barras para mostrar a média de visualizações/vídeo por categoria.
- [ ] Criar um card para mostrar o total de visualizações de todos os vídeos.
- [ ] Criar um card para mostrar o total de vídeos.

# Critérios de Aceitação

## Exportação dos dados

- [ ] Ao clicar no botão de baixar os dados de vídeos, um arquivo .xlsx (excel) com os dados deve ser baixado.
- [ ] Ao clicar no botão de baixar os dados de categorias, um arquivo .xlsx (excel) com os dados deve ser baixado.
- [ ] O botão deve ter a label "Exportar para Excel".

## Criação da Página de Estatísticas por Categoria

- [ ] Ao acessar a página de estatísticas por categoria, o administrador deve ver uma lista de categorias com suas respectivas estatísticas.
- [ ] Os principais dados de cada categoria devem aparecer, como nome, total de visualizações, total de vídeos e média de visualizações/vídeo.

## Criação dos Gráficos

- [ ] Todos os gráficos devem seguir as cores padrões do projeto.
- [ ] Deve aparecer um gráfico de barras para mostrar a média de visualizações por categoria.
- [ ] Deve aparecer um gráfico de pizza para mostrar a proporção de visualizações por categoria.
- [ ] Deve aparecer um gráfico de barras para mostrar a média de vídeos por categoria.
- [ ] Deve aparecer um gráfico de pizza para mostrar a proporção de vídeos por categoria.
- [ ] Deve aparecer um gráfico de barras para mostrar a quantidade de visualizações/vídeo por categoria.
- [ ] Um card com o total de visualizações deve ser visível.
- [ ] Um card com o total de vídeos deve ser visível.

# Protótipo
![image](https://github.com/user-attachments/assets/6da05732-8e04-40bf-aa1f-812aa173cd86)

**Comment by caioleboutte** [comment]
OK
