### ISSUE TITLE
US03 - Eu, como usuário, quero incluir vídeo nas sugestões de pauta, para contribuir na produção e divulgação de vídeos.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#34]
# Tarefas

## Gerais

- [x] Protótipo
- [x] Testes
- [x] Deploy

### 1. Adicionar Campo de URL nas Sugestões de Pauta
- [ ] Adicionar um campo para URL de vídeo no formulário de sugestões de pauta.

### 2. Implementar Validação de URL de Vídeo
- [ ] Validar que a URL inserida é de um dos seguintes serviços de vídeo: YouTube, Google Drive, Microsoft Stream, Streamable e Vimeo.

# Critérios de Aceitação

### 1. Campo de Vídeo nas Sugestões de Pauta
- [ ] O formulário de sugestões de pauta deve incluir um campo para a URL do vídeo.
- [ ] O usuário deve ser capaz de enviar uma sugestão sem preencher o campo de URL, caso desejado.

### 2. Validação de URL de Vídeo
- [ ] Apenas URLs do serviços de vídeo YouTube, Google Drive, Microsoft Stream, Streamable e Vimeo devem ser aceitas.
- [ ] O sistema deve fornecer um alerta, caso a URL não seja válida: "ERRO - A URL (endereço do vídeo) não é válida. Favor corrigir ou deletar".

# Protótipo

## Formulário com URL de vídeo

![prototipo1](https://github.com/user-attachments/assets/3263124d-f281-4a9d-b5ee-718356a77f0f)

## Alerta para tentativa de envio com URL inválida

![prototipo2](https://github.com/user-attachments/assets/033a5bb4-3640-44d1-802a-02d109c07c7e)

**Comment by caioleboutte** [comment]
HOMOLOGADO COM PEQUENO AJUSTE. Trocar o texto de erro para: "ERRO - A URL (endereço do vídeo) não é válida. Favor corrigir ou deletar"

**Comment by victorleaoo** [comment]
https://github.com/fga-eps-mds/2024.1-UnB-TV-Frontend/pull/2
