### ISSUE TITLE
US04 - Eu, como usuário, quero pesquisar vídeos por título, descrição, palavras-chaves e categoria, para encontrar conteúdos específicos.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#35]
# Descrição

Eu, como usuário, quero pesquisar vídeos por título, descrição e categoria, para encontrar conteúdos específicos.

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Campo de pesquisa

- [ ] Criar um único campo de texto na interface de catálogo.
- [ ] Desenvolver que todo texto inserido no campo faça uma busca em todos os vídeos nos atributos de: título, descrição, palavras-chaves e categoria.

## Mostrar os resultados da pesquisa

- [ ] Implementar que os vídeos sejam filtrados a medida que cada caractere de texto for adicionado.
- [ ] Configurar para que quando os vídeos sejam filtrados, eles apareçam em ordem alfábetica direto com sua thumbnail.

# Critérios de Aceitação

## Campo de pesquisa

- [ ] Um único campo de texto está presente na interface de pesquisa.
- [ ] O usuário pode inserir texto neste campo.

## Mostrar os resultados da pesquisa

- [ ] A pesquisa retorna vídeos cujos títulos, descrições, palavras-chaves ou categorias contêm o texto inserido pelo usuário em tempo real.
- [ ] Os vídeos devem aparecer diretamente após serem pesquisados, ordenados por ordem alfabética.

# Protótipo

![image](https://github.com/user-attachments/assets/1b4dab88-f615-41a4-88d5-5ef73f514494)

**Comment by caioleboutte** [comment]
Perfeito. Porém chamo a atenção que a exemplo acima são de lables de programas e não os tumbnails dos próprios. Se clicar em cada lable, abre uma série de tumbs q estes sim, são programas em si. O campo de busca ficar ali, ótimo, mas a resposta com os vídeos q tem os parâmetros de pesquisa deverá vir em outra página.

**Comment by victorleaoo** [comment]
@caioleboutte Nesse caso, o que acha da gente fazer o seguinte para não precisar criar outra tela, nessa de catálogo, quando o campo de busca estiver vazio, ela fica como está agora, mas quando o usuário escrever algo, aí os vídeos acerca da pesquisa vão aparecendo, sem a separação por categoria e programa. Interessante? Ou melhor fazer outra tela mesmo?

**Comment by caioleboutte** [comment]
boa sugestão. usou search, aparece lista de thumbs direto
