### ISSUE TITLE
US08 - Eu, como usuário, quero favoritar um vídeo diretamente da página de visualização, para acessá-lo facilmente depois.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#36]
# Tarefas

## Gerais

- [ ] Protótipo
- [ ] Testes
- [ ] Deploy

## Funcionalidade de Favoritar

- [ ] Adicionar um botão de "Favoritar" na página de visualização de vídeo.
- [ ] Implementar a lógica para adicionar o vídeo à lista de favoritos do usuário ao clicar no botão de "Favoritar" e armazenar essa informação no banco de dados.
- [ ] Garantir que o status de favorito seja atualizado em tempo real e refletido na interface do usuário, mudando a cor para verde e com texto "Tirar Favorito".
- [ ] Adicionar uma mensagem de confirmação ao usuário quando o vídeo for adicionado com sucesso à lista de favoritos.
- [ ] Permitir que o mesmo botão de favoritar seja clicável para remover o vídeo dos favoritos.

# Critérios de Aceitação

## Funcionalidade de Favoritar

- [ ] O botão de "Favoritar" deve estar presente na página de visualização de vídeo.
- [ ] Ao clicar no botão de "Favoritar", o vídeo deve ser adicionado à lista de favoritos do usuário.
- [ ] O status de favorito deve ser atualizado em tempo real e refletido na interface do usuário, mudando a cor para verde e com texto "Tirar Favorito"..
- [ ] Uma mensagem de confirmação deve ser exibida ao usuário quando o vídeo for adicionado com sucesso à lista de favoritos.
- [ ] Quando o botão de "Tirar Favorito" for clicado, o vídeo deve ser removido dos favoritos e o botão volta à configuração de "Favoritar".

# Protótipo
![image](https://github.com/user-attachments/assets/688f85ef-cfe8-4d0a-9bad-27b70728ea96)

**Comment by caioleboutte** [comment]
OK
