### ISSUE TITLE
US09 - Eu, como usuário, quero ver minha lista de vídeos favoritos em um único lugar, para organizar meu conteúdo preferido.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#37]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Desenvolvimento da Listagem de Vídeos Favoritos

- [ ] Adicionar um botão (em padrão de checkbox) para listar apenas os vídeos favoritos na tela de catálogo.
- [ ] Adicionar funcionalidade para listar todos os vídeos favoritos do usuário ao clicar no botão.
- [ ] Integrar com a caixa de pesquisa para pesquisar entre os vídeos favoritos quando eles estiverem selecionados.

# Critérios de Aceitação

## Desenvolvimento da Listagem de Vídeos Favoritos

- [ ] Na tela de catálogo, deve ter um botão em formato de checkbox para listar apenas os vídeos favoritos.
- [ ] Ao clicar no botão de vídeos favoritos deve listar todos os vídeos adicionados pelo usuário.
- [ ] A página deve permitir filtrar e buscar vídeos específicos na lista de favoritos por meio do campo de busca de texto já implementado.

# Protótipo
![image](https://github.com/user-attachments/assets/488406cf-0ff3-458b-a92b-986c7a77ea21)

**Comment by caioleboutte** [comment]
O q vcs acham de acrescentar somente um checkbox ao lado da novo campo que será criado para digitar as keywords de busca? Se selecionar o checkbox, só aparecem os vídeos favoritados. E ainda se selecionar o checkbox, segue tendo a opção de buscar os vídeos favoritados, por palavra chave
