### ISSUE TITLE
US11 - Eu, como usuário, quero ver o histórico de vídeos que assisti recentemente, para encontrar facilmente vídeos que vi anteriormente.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#38]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Desenvolvimento do Histórico

- [ ] Criar uma tabela no banco de dados para armazenar o histórico de vídeos assistidos, com os campos: id, usuario_id, video_id, timestamp.
- [ ] Desenvolver um endpoint no backend que registre o histórico de vídeos assistidos, recebendo usuario_id, video_id e timestamp como parâmetros.
- [ ] Adicionar uma chamada ao endpoint de registro de histórico sempre que um usuário clicar em um vídeo (thumbnail) para assisti-lo.
- [ ] Desenvolver uma nova página no frontend que mostre o histórico de vídeos assistidos pelo usuário, exibindo os vídeos em ordem cronológica decrescente, acessada por meio de um botão "Histórico" na tela de perfil do usuário.

# Critérios de Aceitação

## Desenvolvimento do Histórico

- [ ] O botão "Histórico" deve estar presente na tela de perfil do usuário e deve ser visível e acessível.
- [ ] Ao clicar no botão "Histórico", o usuário deve ser redirecionado para a página de histórico de vídeos assistidos, onde eles serão listados pela sua thumbnail.
- [ ] Os dados do histórico de vídeos devem ser persistentes no banco de dados e devem ser corretamente exibidos mesmo após o usuário fazer logout e login novamente.

# Protótipo
![image](https://github.com/user-attachments/assets/a544aaf4-f2c3-4c3d-82db-87d5d7161356)

Obs.: a princípio nessa história não será adicionado o botão de ordenação por tempo nem a necessidade de não registrar o histórico, isso será tratado em uma US posterior.
