### ISSUE TITLE
US12 - Eu, como usuário, quero configurar minhas preferências de histórico, para gerenciar meu histórico.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#39]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Gerenciamento do histórico

- [x] Implementar um botão em que o usuário ao clicar e confirmar, o seu histórico pode parar de ser rastreado, ou voltar a ser rastreado, dependendo da aplicação.
- [x] Desenvolver lógica para que o usuário possa ou não ter o histórico rastreado dependendo de sua preferência.
- [x] Adicionar botão para ordenar o histórico de forma crescente ou decrescente por dia e hora quando o vídeo foi visto.

# Critérios de Aceitação

## Gerenciamento do histórico

- [ ] Ao clicar no botão de rastreamento do histórico, caso o usuário escolha por não rastrear, os vídeos do histórico devem ser apagados e os novos vídeos vistos não devem ser adicionados.
- [ ] Ao clicar no botão de rastreamento do histórico, caso o usuário escolha por não rastrear, os novos vídeos que ele ver, devem entrar no histórico.
- [ ] Ao clicar no botão de ordenação, ela deve mudar entre crescente e decrescente na listagem do histórico de vídeos do usuário.

# Protótipo
![image](https://github.com/user-attachments/assets/d76520d4-1565-4cb5-87b7-2eed77158674)
