### ISSUE TITLE
US13 - Eu, como usuário, quero marcar vídeos para assistir mais tarde diretamente da página de visualização, para poder guardar uma playlist de vídeos para ver depois.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#40]
# Tarefas

## Gerais

- [ ] Protótipo
- [ ] Testes
- [ ] Deploy

## Funcionalidade de "Assistir Mais Tarde"

- [ ] Adicionar um botão de "Assistir Mais Tarde" na página de visualização de vídeo.
- [ ] Implementar a lógica para adicionar o vídeo à lista de "Assistir Mais Tarde" do usuário ao clicar no botão de "Assistir Mais Tarde" e armazenar essa informação no banco de dados.
- [ ] Garantir que o status de "Assistir Mais Tarde" seja atualizado em tempo real e refletido na interface do usuário, mudando a cor do botão e com texto "Remover da Lista".
- [ ] Adicionar uma mensagem de confirmação ao usuário quando o vídeo for adicionado com sucesso à lista de "Assistir Mais Tarde".
- [ ] Permitir que o mesmo botão de "Assistir Mais Tarde" seja clicável para remover o vídeo da lista de "Assistir Mais Tarde".

# Critérios de Aceitação

## Funcionalidade de "Assistir Mais Tarde"

- [ ] O botão de "Assistir Mais Tarde" deve estar presente na página de visualização de vídeo.
- [ ] Ao clicar no botão de "Assistir Mais Tarde", o vídeo deve ser adicionado à lista de "Assistir Mais Tarde" do usuário.
- [ ] O status de "Assistir Mais Tarde" deve ser atualizado em tempo real e refletido na interface do usuário, mudando a cor do botão e com texto "Remover da Lista".
- [ ] Uma mensagem de confirmação deve ser exibida ao usuário quando o vídeo for adicionado com sucesso à lista de "Assistir Mais Tarde".
- [ ] Quando o botão de "Remover da Lista" for clicado, o vídeo deve ser removido da lista de "Assistir Mais Tarde" e o botão volta à configuração de "Assistir Mais Tarde".

![image](https://github.com/user-attachments/assets/dfff3cbf-2d1a-409a-ae28-5417e8e7140f)

**Comment by caioleboutte** [comment]
OK
