### ISSUE TITLE
US14 - Eu, como usuário, quero acessar minha lista de vídeos para assistir mais tarde, para poder encontrar facilmente os vídeos que marquei para ver depois.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#41]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Desenvolvimento da Listagem de Vídeos em "Assistir Mais Tarde"

- [x] Adicionar um botão (em padrão de checkbox) para listar apenas os vídeos marcados como "Assistir Mais Tarde" na tela de catálogo.
- [x] Adicionar funcionalidade para listar todos os vídeos adicionados como "Assistir Mais Tarde" do usuário ao clicar no botão.
- [x]  Integrar com a caixa de pesquisa para pesquisar entre os vídeos em "Assistir Mais Tarde" quando eles estiverem selecionados.

# Critérios de Aceitação

## Desenvolvimento da Listagem de Vídeos em "Assistir Mais Tarde"

- [ ] Na tela de catálogo, deve ter um botão em formato de checkbox para listar apenas os vídeos salvos como "Assistir Mais Tarde".
- [ ] Ao clicar no botão de vídeos "Assistir Mais Tarde" deve listar todos os vídeos adicionados pelo usuário.
- [ ] A página deve permitir filtrar e buscar vídeos específicos na lista por meio do campo de busca de texto já implementado.

# Protótipo

![image](https://github.com/user-attachments/assets/1492a887-c690-4afd-af42-65fecf8d9785)

**Comment by caioleboutte** [comment]
OK
