### ISSUE TITLE
US15 - Eu, como usuário, quero ter telas personalizadas a partir da tela de "Sua UnBTV", para visualizar conteúdos relacionados a mim.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#42]
# Tarefas

## Gerais

- [ ] Protótipo
- [ ] Testes
- [ ] Deploy

## Desenvolvimento da tela "Sua UnBTV"

- [ ] Mudar o menu superior de navegação para substituir "Programação" por "Sua UnBTV".
- [ ] Na página de "Sua UnBTV", adicionar botões para as telas de "recomendações", "histórico", "favoritos" e "assista mais tarde".
- [ ] Implementar cada página com título dela e a listagem dos vídeos baseados na funcionalidade chamada.

# Critérios de Aceitação

- [ ] O usuário apenas consegue acessar a tela se estiver logado, se não, ele deve ser redirecionado para a tela de login.
- [ ] O usuário, ao clicar no menu superior em "Sua UnBTV", é direcionado para a nova tela.
- [ ] O usuário é capaz de ver os 4 botões de: "recomendações", "histórico", "favoritos" e "assista mais tarde".
- [ ] Ao clicar em cada botão, o usuário é redirecionado para uma tela que contém o título da tela e a listagem dos vídeos respectivos à funcionalidade selecionada.

# Protótipo
![image](https://github.com/user-attachments/assets/d6f1295d-2f06-4aa4-bb90-a6e0f7d8441c)
