### ISSUE TITLE
US16  - Eu, como usuário, quero receber notificações de novos vídeos recomendados para mim, para estar sempre atualizado com novos conteúdos.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#43]
# Tarefas

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

### Sistema de Notificações
- [x] Implementar um sistema de notificações que envie alertas ao usuário sobre novos vídeos recomendados.
- [x] Desenvolver uma funcionalidade para marcar as notificações como lidas ou ignoradas pelo usuário.

### Interface do Usuário
- [x] Implementar um ícone de notificação na barra de navegação que mostre o número de novas notificações não lidas.
- [x] Desenvolver um mecanismo para que o usuário possa acessar diretamente o vídeo recomendado a partir da notificação.

### Sistema de Notificações
- [ ] O usuário deve receber notificações automáticas sobre novos vídeos recomendados com base em seu histórico e preferências.
- [ ] As notificações devem ser enviadas assim que novos vídeos forem adicionados que correspondam aos interesses do usuário.
- [ ] O usuário deve poder marcar as notificações como lidas ou ignorá-las.

### Interface do Usuário
- [ ] A interface deve exibir claramente as notificações de novos vídeos recomendados em uma área designada.
- [ ] O usuário deve poder clicar na notificação e ser direcionado diretamente ao vídeo recomendado.

# Protótipo
![notificacaoUNBTV](https://github.com/user-attachments/assets/8d8626ea-f101-4630-b988-dd66ba776b16)
