### ISSUE TITLE
US18 - Eu, como usuário, quero a opção de pular para o próximo vídeo, para ter uma experiência contínua de visualização.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#45]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Pular para próximo vídeo

- [ ] Implementar um botão na interface de vídeo para pular para o próximo vídeo, com o nome de "Próximo Vídeo ->".
- [ ] Implementar lógica para que o próximo vídeo seja um vídeo do mesmo programa que o usuário está vendo, ou da mesma categoria, caso não hajam mais vídeos do programa.
- [ ] Desenvolver mecanismo para que, ao passar o mouse no botão, seja possível ver o título do próximo vídeo.

# Critérios de Aceitação

## Gerenciamento do histórico

- [ ] O botão de "Próximo Vídeo ->" deve estar visível e acessível na tela de vídeo.
- [ ] Ao passar o mouse em cima do botão, é possível visualizar o título do próximo vídeo.
- [ ] Ao clicar no próximo vídeo, ele deve ser do mesmo programa que o vídeo anterior, ou pelo menos da mesma categoria, caso seja o último vídeo do programa que estava sendo visto.

# Protótipo

![image](https://github.com/user-attachments/assets/1607422d-1d94-4607-91ff-f0687eff0651)
