### ISSUE TITLE
US10 - Eu, como administrador, quero gerenciar cargos de co-administradores, para delegar responsabilidades de gerenciamento.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/2024.1-UnB-TV-DOC#47]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

## Configuração de Permissões

- [ ] Implementar um sistema de gerenciamento de cargos para co-administradores.
- [ ] Adicionar a capacidade de definir permissões específicas para cada co-administrador.
- [ ] Configurar uma interface de gerenciamento para que o administrador principal possa adicionar, editar ou remover co-administradores.

## Configuração de Permissões

- [ ] Criar uma página dedicada ao gerenciamento de cargos de co-administradores.
- [ ] Adicionar funcionalidades para listar todos os co-administradores e suas respectivas permissões.
- [ ]  Implementar funcionalidades de filtro e busca para facilitar a localização de co-administradores específicos.

# Critérios de Aceitação

- [ ] Cada co-administrador deve ter permissões claramente definidas que determinam o que ele pode e não pode fazer no sistema.
- [ ] O administrador principal deve conseguir remover co-administradores através da interface de gerenciamento.
- [ ] O sistema deve restringir o acesso a página somente para quem tiver a role ADMIN.
- [ ] O usuário que não tiver a role ADMIN, caso tente acessar a página, será redirecionado e receberá um alerta de permissão negada na tela.
# Protótipo
![image](https://github.com/user-attachments/assets/aa708a48-c425-42e2-b646-5851b41f95b7)
