### ISSUE TITLE
Dojo: Fullstack

### ISSUE THREAD

**Issue by victorleaoo** [fga-eps-mds/2024.1-UnB-TV-DOC#55]
Tarefa:

- [ ] Realização do DOJO
    - [ ] Funcionamento Angular + FastAPI
- [ ] Disponibilizar no Pages
