### ISSUE TITLE
Dojo: Backend

### ISSUE THREAD

**Issue by victorleaoo** [fga-eps-mds/2024.1-UnB-TV-DOC#57]
Tarefa:

- [x] Realização do DOJO
    - [x] Backend - REST API
- [x] Disponibilizar no Pages
