### ISSUE TITLE
US20 - Eu, como administrador, gostaria de uma página de acesso próprio, para que eu possa ter acesso a dados e informações sigilosos.

### ISSUE THREAD

**Issue by victorleaoo** [fga-eps-mds/2024.1-UnB-TV-DOC#60]
# Descrição

Eu, como administrador, gostaria de uma página de acesso próprio, para que eu possa ter acesso a dados e informações sigilosos.

# Tarefas

## Gerais

- [x] Protótipo
- [x] Testes
- [x] Deploy

## Configuração de Autenticação

- [ ] Implementar um sistema de autenticação para garantir que apenas administradores possam acessar a página.
- [ ] Configurar a interface de login com validação de credenciais.
- [ ] Implementar um sistema de "log-out" para o administrador sair da sua página.

## Cadastro para perfil de administrador

- [ ] Adaptar o e-mail de ativação para quando um usuário se cadastrar com o e-mail da UnB, ele receber um link caso deseje ser admin, no qual ele pode se logar como admin (mesmo e-mail e senha já cadastrado).
- [ ] Redirecionar o usuário cadastrado para a tela inicial de admin.

## Desenvolvimento da Página Inicial

- [ ] Implementar a página inicial do administrador, que lista as páginas disponíveis a ele.
- [ ] Construir um menu inicial com direcionamento para as outras páginas disponíveis.

# Critérios de Aceitação

## Configuração de Autenticação

- [ ] Somente usuários com permissões de administrador devem conseguir acessar a página restrita.
- [ ] A interface de login deve permitir a inserção de e-mail e senha e retornar erro, caso não esteja cadastrado no banco de dados.
- [ ] Deve haver uma opção de "log-out" claramente visível na página inicial do administrador.
- [ ] Após o log-out, o administrador deve ser redirecionado para a página de login.

## Cadastro para perfil de administrador

- [ ] Ao cadastrar o novo usuário com e-mail UnB, receber no e-mail de ativação link para se tornar admin.
- [ ] Ao clicar no link para se tornar admin, ser direcionado para a página de login de admin, em que ele pode se logar, caso a conta já tenha sido ativada.
- [ ] Após isso, ser redirecionado para a página de admin.

## Desenvolvimento da Página Inicial

- [ ] A página inicial deve exibir uma lista clara e organizada das páginas disponíveis ao administrador.
- [ ] Cada item da lista deve ser clicável e redirecionar para a página correspondente.
- [ ] O menu deve conter links para todas as páginas disponíveis ao administrador.

# Protótipos

## Página Inicial
![image](https://github.com/user-attachments/assets/5ddf11cc-0b9e-431b-ba24-02e1f375a761)

**Comment by caioleboutte** [comment]
HOMOLOGADO COM CORREÇÕES. 1. Não concordo com abrir uma opção no cadastro. a grande maioria dos usuários não irá usar esta info e é mais algo p navegar....ter problema....etc...Sugiro o seguinte: quando for um novo usuário se cadastrando com email UnB, no e-mail de confirmação do endereço de e-mail, este e-mail enviar link padrão de confirmação de usuário e, no mesmo e-mail, outro link com "caso vc seja adm, clique aqui". E aí faz a homologação do adm, em outro ambiente. (sugestão.....para debatermos) 2. não precisa se preocupar com já transformar os dados em um dashboard "bonito" e amigável. sugiro q a apresentação seja layout tabela msm e com opção para exportar estes dados como planilha para os dados serem trabalhados fora do ambiente do APP. aí usaremos as opções de tabulação do excel ou qq outra ferramenta com todos os mil cruzamentos possíveis.

**Comment by victorleaoo** [comment]
@caioleboutte Corrigimos propondo:
1. Ao usuário cadastrar com e-mail da unb, o e-mail de ativação vir com um link para se tornar admin, em que nesse link, então, ele teria que cadastrar uma outra senha mais robusta e, assim, poderia acessar a página de admin com maior segurança para os dados.
2. Essa página inicial não seria um dashboard e sim, mas uma página para redirecionar às outras. Assim, adaptei o protótipo, caso queira conferir... seriam botões para as outras páginas que criássemos nessa área de admin.

Alguma outra sugestão?

**Comment by caioleboutte** [comment]
Olá,
1. é mesmo necessário ser outra senha? A priori, acho ruim sair do padrão. pensei em, para dar maior segurança, permitir q o ADM só consiga logar quando no wifi da UnB. é possível? temos sistemas na unversidade q funcionam assim. restringem pela rede q vc está acessando. ex: ponto eletronico é acessado via browser e só consegue ser batido o ponto quando o funcionário está na logado no wifi da UnB.

**Comment by caioleboutte** [comment]
2. OK. blz

Obrigado!!

**Comment by victorleaoo** [comment]
> Olá,
> 
> 1. é mesmo necessário ser outra senha? A priori, acho ruim sair do padrão. pensei em, para dar maior segurança, permitir q o ADM só consiga logar quando no wifi da UnB. é possível? temos sistemas na unversidade q funcionam assim. restringem pela rede q vc está acessando. ex: ponto eletronico é acessado via browser e só consegue ser batido o ponto quando o funcionário está na logado no wifi da UnB.

@caioleboutte, podemos manter então a mesma senha de 6 digitos. Aqui do grupo, confessamos que não sabemos muito bem como implementar essa verificação de wifi de forma a trazer já esse entregável nessa release ou em tempo hábil do projeto... 

Sugerimos, então, manter a senha de 6 dígitos, o usuário que tem e-mail UnB, recebe no e-mail além da ativação, a possibilidade de se tornar admin. O que acha de fazermos assim nesse primeiro momento, para trabalharmos com a entrega dessa página e, depois, conversamos sobre essa questão da autenticação? Porque uma vez implementada a página, mudar a autenticação é relativamente mais simples, já que o código "core" já vai estar pronto.

**Comment by caioleboutte** [comment]
Fechado! Desculpas pela demora na resposta!
