### ISSUE TITLE
US21 - Eu, como usuário, quero que o sistema recomende vídeos semelhantes aos que já assisti, para que eu possa descobrir novos conteúdos relacionados.

### ISSUE THREAD

**Issue by victorleaoo** [fga-eps-mds/2024.1-UnB-TV-DOC#63]
# Tarefas

## Gerais

- [ ] Protótipo
- [ ] Testes
- [ ] Deploy

## Limpeza e transformação dos dados

- [ ] Coletar os dados textuais de vídeos: título, descrição, categoria e palavras-chaves.
- [ ] Realizar limpeza, removendo pontuação, *stop words* e normalizações de capitalização.
- [ ] Promover a tokenização e vetorização para transformar os textos em números.
- [ ] Criar combinações de vídeos de histórico de usuários para teste.

## Testes de modelo de recomendação

- [ ] Testar diferentes combinações, incluindo categoria e palavra-chave como OU não atributos a mais na recomendação por parte do recomendador.
- [ ] Testar diferentes modelos de recomendação para entender os diferentes resultados:
    - [ ] Cosine similarity.
    - [ ] KNeighbors.
    - [ ] BERT.
- [ ] Avaliar modelo com melhor resultado e parâmetros para uso.

## Pipeline final

- [ ] Integrar o modelo com o histórico real dos usuários em um endpoint no backend.
- [ ] Testar viabilidade real com tempo de processamento do modelo.

# Critérios de Aceitação

## Modelo de recomendação

- [ ]

# Protótipo
