### ISSUE TITLE
US22 - Eu, como usuário, quero a opção de pular para o próximo vídeo recomendado, para ter uma experiência contínua de visualização.

### ISSUE THREAD

**Issue by GabrielRoger07** [fga-eps-mds/2024.1-UnB-TV-DOC#65]
# Tarefas

## Gerais

- [ ] Protótipo
- [ ] Testes
- [ ] Deploy

## Pular para próximo vídeo

- [ ] Implementar lógica para que o próximo vídeo seja um vídeo recomendado para o usuário.
- [ ] Desenvolver mecanismo para que, ao passar o mouse no botão, seja possível ver o título do próximo vídeo.

# Critérios de Aceitação

## Gerenciamento do histórico

- [ ] Ao passar o mouse em cima do botão, é possível visualizar o título do próximo vídeo.
- [ ] Ao clicar no próximo vídeo, ele deve ser baseado nas recomendações para o usuário.

# Protótipo

![image](https://github.com/user-attachments/assets/48e8531a-b395-4417-b9c7-642ae0c4489c)
