### ISSUE TITLE
US05 - Eu, como administrador, quero alterar os cargos de outros usuários por meio da tela de administrador.

### ISSUE THREAD

**Issue by GabrielRoger07** [fga-eps-mds/2024.1-UnB-TV-DOC#67]
# Tarefas

## Gerais

- [x] Protótipo
- [ ] Testes
- [ ] Deploy

### Implementação
- [ ] Implementar um sistema de gerenciamento de cargos para co-administradores.
- [ ] Adicionar a capacidade de definir permissões específicas para cada co-administrador.
- [ ] Configurar uma interface de gerenciamento para que o administrador
- [ ] Permitir a alteração da ROLE de forma prática e intuitiva 

### Página de Gerenciamento
- [ ] Criar uma página dedicada ao gerenciamento de cargos de co-administradores.
- [ ] Adicionar funcionalidades para listar todos os co-administradores e suas respectivas permissões.

## Critérios de Aceitação

- [ ] Cada co-administrador deve ter permissões claramente definidas que determinam o que ele pode e não pode fazer no sistema.
- [ ] O administrador principal deve conseguir remover co-administradores através da interface de gerenciamento.
- [ ] O sistema deve restringir o acesso à página somente para quem tiver a role ADMIN.
- [ ] O usuário que não tiver a role ADMIN, caso tente acessar a página, será redirecionado

# Protótipo
![image](https://github.com/user-attachments/assets/2981d24a-9d8b-457b-937a-5e880cb0a501)
