### ISSUE TITLE
Alterações sugeridas pós entrega da R2

### ISSUE THREAD

**Issue by victorleaoo** [fga-eps-mds/2024.1-UnB-TV-DOC#68]
Alterações:

- [ ] Alteração no funcionamento do filtro de categorias da tela "Dados - Categorias";
- [ ] Alteração no funcionamento do filtro de categorias da tela "Dados - Vídeos";
- [ ] Adição de validação do campo telefone na sugestão de pauta;
- [ ] Ajuste no CSS das checkboxs "Assistir mais tarde" e "Listar Favoritos" do catálogo de vídeos;
- [ ] Ajuste na fonte da tela "Dashboard - Categorias".
