### ISSUE TITLE
US23 - Eu, como usuário, quero excluir um vídeo do histórico, para gerenciar o histórico.

### ISSUE THREAD

**Issue by GabrielRoger07** [fga-eps-mds/2024.1-UnB-TV-DOC#71]
# Tarefas

## Gerais

- [ ] Protótipo
- [ ] Testes
- [ ] Deploy

## Gerenciamento do histórico

- [ ] Implementar um botão em cada vídeo em que o usuário, ao clicar e confirmar, remove o vídeo do histórico rastreado.
- [ ] Desenvolver lógica para que o usuário possa excluir um vídeo em específico do histórico rastreado.

# Critérios de Aceitação

## Gerenciamento do histórico

- [ ] Ao clicar no botão de excluir um vídeo do histórico, caso o usuário escolha por rastrear, o vídeo deve ser removido do histórico.

# Protótipo

![image](https://github.com/user-attachments/assets/cd92102d-fb2e-48e0-851f-0c5be8c4214c)
